version: '3'

services:

  db:
   image: mysql:5.7.21
   restart: always
   environment:
    MYSQL_USER: me
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: data
   ports:
   - "8100:8100"

#docker-compose up
